apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockserver
  template:
    metadata:
      labels:
        app: mockserver
    spec:
      containers:
      - name: mockserver
        image: microcks/microcks-uber:latest-native
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mockserver
spec:
  selector:
    app: mockserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
