openapi: 3.0.2
info:
  title: Payment Gateway API
  version: 1.0.0
components:
  schemas:
    Payment:
      allOf:
        - $ref: "#/components/schemas/NewPayment"
        - properties:
            transactionId:
              format: string
              type: string
          required:
            - transactionId
    NewPayment:
      properties:
        orderId:
          type: string
        amount:
          type: number
      required:
        - orderId
        - amount

paths:
  /processPayment:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPayment"
            examples:
              new_payment:
                value:
                  orderId: "123"
                  amount: 100.00
      responses:
        "201":
          description: Payment processed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payment"
              examples:
                payment_success:
                  value: |-
                    {
                      "transactionId": "{{ randomUUID() }}",
                      "orderId": "{{ request.body/orderId }}",
                      "amount": "{{ request.body/amount }}",
                      "status": "success"
                    }